# Site settings
title: Jonathan Wheeler
tagline: Equip others to help care for the world.
email: jonathan.m.wheeler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stanford EE Masters student, polyglot, software engineer, Christian, Bitcoin enthusiast, friend.
  I blog about my discoveries and lessons learned
  in order to pay back to those who invested in me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jamwheeler.com" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Jonathan Wheeler"
author_thumbnail: "/assets/images/jon.png" # Author avatar
# Theme customization - please change from the defaults!
theme_settings:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: wheelerj
    twitter: jondoesnttweet
    facebook: jondoesntpost
    #gplus: +gayanvirajith
    # dribble: gayanvirajith
    # pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
gems: [jekyll-paginate]
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
