# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jonathan Wheeler
email: jonathan dot m dot wheeler at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  I study how light can be used for navigation, both for
   inertial navigation of aircraft, and for navigating challenges
   of this life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jamwheeler.com" # the base hostname & protocol for your site, e.g. http://example.com
author: "Jonathan Wheeler"
author_thumbnail: "/assets/images/jon.png" # Author avatar
twitter_username: jondoesnttweet
github_username:  jondoesntgit
facebook_username: jondoesntpost
linkedin_username: jondoesntlink
instagram_username: jondoesntig

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - .sass-cache

include: ['_pages']